# Generated by Django 2.2 on 2021-06-07 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shows',
            new_name='Show',
        ),
    ]
